<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "typo3_7timer_extension"
 *
 * Auto generated by Extension Builder 2021-07-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '7Timer Extension',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Thomas Ludwig',
    'author_email' => 'admin@eliteschw31n.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
